// Generated by CoffeeScript 1.10.0
(function() {
  var controller;

  controller = require("./starttimes.controller");

  module.exports = function(router) {
    router.get("/starttimes", controller.index);
    router.get("/starttimes/:id", controller.show);
    router.post("/starttimes", controller.create);
    router.put("/starttimes/:id", controller.update);
    router.patch('/starttimes/:id', controller.update);
    return router["delete"]('/starttimes/:id', controller.destroy);
  };

}).call(this);

//# sourceMappingURL=index.js.map
