// Generated by CoffeeScript 1.10.0
(function() {
  var auth, controller;

  controller = require("./users.controller");

  auth = require('../../auth/auth.service');

  module.exports = function(router) {
    router.get("/users", auth.hasRole('admin'), controller.index);
    router["delete"]("/users/:id", auth.hasRole('admin'), controller.destroy);
    router.get("/users/me", auth.isAuthenticated(), controller.me);
    router.put('/users/:id/password', auth.isAuthenticated(), controller.changePassword);
    router.get('/users/:id', auth.isAuthenticated(), controller.show);
    return router.post('/users', controller.create);
  };

}).call(this);

//# sourceMappingURL=index.js.map
