// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('InterCityBus').config(function($stateProvider) {
    return $stateProvider.state('admin', {
      url: '/admin',
      templateUrl: '/admin/admin.html',
      controller: 'AdminCtrl'
    });
  });

}).call(this);
