// Generated by CoffeeScript 1.10.0
(function() {
  var busline, city, company, phone, station;

  busline = require("./buslines");

  city = require("./cities");

  company = require("./companies");

  phone = require("./phones");

  station = require("./stations");

  module.exports = function(router) {
    busline(router);
    city(router);
    company(router);
    phone(router);
    return station(router);
  };

}).call(this);

//# sourceMappingURL=index.js.map
