// Generated by CoffeeScript 1.10.0
(function() {
  var busline, city, company, phone, starttimes, station, users;

  busline = require("./buslines");

  city = require("./cities");

  company = require("./companies");

  phone = require("./phones");

  station = require("./stations");

  starttimes = require("./starttimes");

  users = require("./users");

  module.exports = function(router) {
    busline(router);
    city(router);
    company(router);
    phone(router);
    station(router);
    starttimes(router);
    return users(router);
  };

}).call(this);

//# sourceMappingURL=index.js.map
