// Generated by CoffeeScript 1.9.3
(function() {
  var controller;

  controller = require("./buslines.controller");

  module.exports = function(router) {
    router.get("/test", function(req, res, next) {
      return res.send("test ok");
    });
    router.get("/buslines", controller.index);
    router.get("/buslines/:id", controller.show);
    router.put("/buslines/:id", controller.update);
    return router.patch('/buslines/:id', controller.update);
  };

}).call(this);
