// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('InterCityBus').config(function($stateProvider) {
    return $stateProvider.state('feedback', {
      url: '/feedback',
      templateUrl: 'app/feedback/feedback.html',
      controller: 'FeedbackController'
    });
  });

}).call(this);

//# sourceMappingURL=feedback.js.map
