// Generated by CoffeeScript 1.10.0
(function() {
  var controller;

  controller = require("./companies.controller");

  module.exports = function(router) {
    router.get("/companies", controller.index);
    router.get("/companies/:id", controller.show);
    router.post("/companies", controller.create);
    router.put("/companies/:id", controller.update);
    router.patch('/companies/:id', controller.update);
    return router["delete"]('/companies/:id', controller.destroy);
  };

}).call(this);

//# sourceMappingURL=index.js.map
