// Generated by CoffeeScript 1.10.0
(function() {
  var concat, gulp, ngmin, rename, uglify;

  gulp = require('gulp');

  ngmin = require("gulp-ngmin");

  concat = require("gulp-concat");

  uglify = require("gulp-uglify");

  rename = require("gulp-rename");

  gulp.task('default', function() {
    return gulp.src(["client/app/**/*.js", '!client/app/admin/**/*.js']).pipe(ngmin()).pipe(concat("sb.js")).pipe(gulp.dest("dest")).pipe(uglify()).pipe(rename({
      extname: ".min.js"
    })).pipe(gulp.dest("dest"));
  });

}).call(this);

//# sourceMappingURL=gulpfile.js.map
