// Generated by CoffeeScript 1.9.3
(function() {
  var controller;

  controller = require("./busline.controller");

  module.exports = function(router) {
    router.get("/test", function(req, res, next) {
      return res.send("test ok");
    });
    return router.get("/buslines", controller.index);
  };

}).call(this);
