// Generated by CoffeeScript 1.10.0
(function() {
  var auth, controller;

  controller = require("./phones.controller");

  auth = require('../../auth/auth.service');

  module.exports = function(router) {
    router.get("/phones", auth.hasRole('admin'), controller.index);
    router.get("/phones/:id", auth.hasRole('admin'), controller.show);
    router.post("/phones", auth.hasRole('admin'), controller.create);
    router.put("/phones/:id", auth.hasRole('admin'), controller.update);
    router.patch('/phones/:id', auth.hasRole('admin'), controller.update);
    return router["delete"]('/phones/:id', auth.hasRole('admin'), controller.destroy);
  };

}).call(this);

//# sourceMappingURL=index.js.map
