// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('InterCityBus').config(function($stateProvider) {
    return $stateProvider.state('requestlines', {
      url: '/admin/requestlines',
      templateUrl: 'app/admin/requestlines/requestlines.html',
      controller: 'RequestLinesListCtrl'
    });
  });

}).call(this);

//# sourceMappingURL=requestlines.js.map
