// Generated by CoffeeScript 1.10.0
(function () {
  var myapp;
  myapp = angular.module('InterCityBus', [
    'ui.router',
    'ngCookies',
    'ngResource',
    'InterCityBus.services',
    'InterCityBus.controllers'
  ]).config([
    '$stateProvider',
    '$urlRouterProvider',
    '$locationProvider',
    '$httpProvider',
    function ($stateProvider, $urlRouterProvider, $locationProvider, $httpProvider) {
      $locationProvider.html5Mode(true);
      return $httpProvider.interceptors.push('authInterceptor');
    }
  ]).factory('authInterceptor', [
    '$rootScope',
    '$q',
    '$cookies',
    '$injector',
    function ($rootScope, $q, $cookies, $injector) {
      return {
        request: function (config) {
          config.headers = config.headers || {};
          if ($cookies.get('token')) {
            config.headers.Authorization = 'Bearer ' + $cookies.get('token');
          }
          return config;
        },
        responseError: function (response) {
          var state;
          if (response.status === 401) {
            (state || (state = $injector.get('$state'))).go('login');
            $cookies.remove('token');
            return $q.reject(response);
          } else {
            return $q.reject(response);
          }
        }
      };
    }
  ]).run([
    '$rootScope',
    '$state',
    function ($rootScope, $state) {
      return $rootScope.$on('$stateChangeStart', function (event, next) {
        console.log(next);
        console.log(next.url);
        if (next.url === '/') {
          event.preventDefault();
          return $state.go('search');
        }
      });
    }
  ]);
  angular.module('InterCityBus.services', []);
  angular.module('InterCityBus.controllers', []);
}.call(this));  //# sourceMappingURL=app.js.map

// Generated by CoffeeScript 1.10.0
(function () {
  angular.module('InterCityBus').controller('BuslineController', [
    '$scope',
    '$window',
    '$document',
    '$stateParams',
    '$http',
    '$timeout',
    '$interval',
    'Busline',
    'Utils',
    function ($scope, $window, $document, $stateParams, $http, $timeout, $interval, Busline, Utils) {
      $scope.dial = function (phone) {
        var handler;
        $timeout(function () {
          return $scope.finishBook = true;
        }, 5000);
        handler = $window.open('tel:' + phone);
        return false;
      };
      $scope.purify = function (str) {
        return str.replace(/\s+/g, '');
      };
      $scope.busline = Busline.get({ id: $stateParams.id });
      $scope.$on('$viewContentLoaded', function (event) {
        $timeout(function () {
          return Utils.fixTooLongIssue();
        }, 100);
        $timeout(function () {
          return Utils.fixTooLongIssue();
        }, 500);
        return $timeout(function () {
          return Utils.fixTooLongIssue();
        }, 2000);
      });
      $scope.closeit = function () {
        return $scope.finishBook = false;
      };
      return $scope.shareit = function () {
        $scope.shareIt = true;
        return $timeout(function () {
          return $scope.shareIt = false;
        }, 10000);
      };
    }
  ]);
}.call(this));  //# sourceMappingURL=busline.controller.js.map

// Generated by CoffeeScript 1.10.0
(function () {
  angular.module('InterCityBus').config([
    '$stateProvider',
    function ($stateProvider) {
      return $stateProvider.state('busline', {
        url: '/busline/:id',
        templateUrl: 'app/busline/busline.html',
        controller: 'BuslineController'
      });
    }
  ]);
  angular.module('InterCityBus.services').factory('Busline', [
    '$resource',
    function ($resource) {
      return $resource('/api/buslines/:id', { id: '@id' }, { update: { method: 'PUT' } });
    }
  ]);
}.call(this));  //# sourceMappingURL=busline.js.map

// Generated by CoffeeScript 1.10.0
(function () {
  angular.module('InterCityBus').controller('FeedbackController', [
    '$scope',
    '$http',
    function ($scope, $http) {
      return $scope.submitFeedback = function () {
        return alert('\u60a8\u7684\u53cd\u9988\u6211\u4eec\u5df2\u7ecf\u6536\u5230\uff01');
      };
    }
  ]);
}.call(this));  //# sourceMappingURL=feedback.controller.js.map

// Generated by CoffeeScript 1.10.0
(function () {
  angular.module('InterCityBus').config([
    '$stateProvider',
    function ($stateProvider) {
      return $stateProvider.state('feedback', {
        url: '/feedback',
        templateUrl: 'app/feedback/feedback.html',
        controller: 'FeedbackController'
      });
    }
  ]);
}.call(this));  //# sourceMappingURL=feedback.js.map

// Generated by CoffeeScript 1.10.0
(function () {
  angular.module('InterCityBus').controller('IndexController', [
    '$state',
    '$rootScope',
    '$scope',
    '$timeout',
    '$http',
    'City',
    'Hotline',
    function ($state, $rootScope, $scope, $timeout, $http, City, Hotline) {
      $scope.$on('$stateChangeSuccess', function (ev, to, toParams, from, fromParams) {
        if (to.name === 'index' && fromParams.start && fromParams.end) {
          return $scope.cities.$promise.then(function () {
            $scope.startCity = $scope.cities[fromParams.start - 1];
            return $scope.endCity = $scope.cities[fromParams.end - 1];
          });
        }
      });
      $scope.swapCity = function () {
        var tmp;
        tmp = this.startCity;
        this.startCity = this.endCity;
        return this.endCity = tmp;
      };
      $scope.cities = City.query();
      $scope.hotlines = Hotline.query({ limit: 6 });
      $scope.search = function (start, end) {
        return $state.go('search', {
          start: start,
          end: end
        });
      };
      return $scope.searchBusline = function () {
        if (!this.startCity || !this.endCity) {
          alert('\u5fc5\u987b\u9009\u597d\u51fa\u53d1\u548c\u7ec8\u70b9\u57ce\u5e02\u54e6');
          return;
        }
        if (this.startCity.id === this.endCity.id) {
          alert('\u51fa\u53d1\u5730\u548c\u7ec8\u70b9\u5730\u4e0d\u80fd\u4e00\u6837\u54e6');
          return;
        }
        return $state.go('search', {
          start: this.startCity.id,
          end: this.endCity.id
        });
      };
    }
  ]);
}.call(this));  //# sourceMappingURL=index.controller.js.map

// Generated by CoffeeScript 1.10.0
(function () {
  angular.module('InterCityBus').config([
    '$stateProvider',
    function ($stateProvider) {
      return $stateProvider.state('index', {
        url: '/index',
        templateUrl: 'app/index/index.html',
        controller: 'IndexController'
      });
    }
  ]);
  angular.module('InterCityBus.services').factory('City', [
    '$resource',
    function ($resource) {
      return $resource('/api/cities/:id', { id: '@id' }, { update: { method: 'PUT' } });
    }
  ]).factory('Hotline', [
    '$resource',
    function ($resource) {
      return $resource('/api/hotlines/:id', { id: '@id' });
    }
  ]);
}.call(this));  //# sourceMappingURL=index.js.map

// Generated by CoffeeScript 1.10.0
(function () {
  angular.module('InterCityBus').controller('SearchController', [
    '$state',
    '$scope',
    '$window',
    '$stateParams',
    '$http',
    '$timeout',
    'City',
    'Hotline',
    'Busline',
    'Utils',
    function ($state, $scope, $window, $stateParams, $http, $timeout, City, Hotline, Busline, Utils) {
      $scope.cities = City.query();
      $scope.startCityId = $stateParams.start;
      $scope.endCityId = $stateParams.end;
      $scope.buslines = Busline.query({
        start: $stateParams.start,
        end: $stateParams.end
      }, function () {
        return $scope.showNoResult = $scope.buslines.length === 0;
      });
      $scope.viewDetailBusline = function (id) {
        return $state.go('busline', { id: id });
      };
      angular.element($window).bind('orientationchange', function () {
        return $timeout(function () {
          return Utils.fixTooLongIssue();
        }, 500);
      });
      angular.element($window).bind('resize', function () {
        return $timeout(function () {
          return Utils.fixTooLongIssue();
        }, 500);
      });
      $scope.$on('$viewContentLoaded', function (event) {
        $timeout(function () {
          return Utils.fixTooLongIssue();
        }, 100);
        $timeout(function () {
          return Utils.fixTooLongIssue();
        }, 500);
        return $timeout(function () {
          return Utils.fixTooLongIssue();
        }, 2000);
      });
      $scope.research = function () {
        return $state.go('index');
      };
      return $scope.requestNewLine = function () {
        var end, msg, requestline, start;
        start = $scope.cities[$scope.startCityId - 1].name;
        end = $scope.cities[$scope.endCityId - 1].name;
        msg = '\u60a8\u4e13\u5c5e\u5b9a\u5236\u7684' + start + '-' + end + '\u7684\u8def\u7ebf\u5c0f\u5df4\u5df2\u7ecf\u6536\u5230\uff0c\u5c06\u4f1a\u5c3d\u5feb\u5f00\u901a\uff0c\u5c4a\u65f6\u5c06\u7b2c\u4e00\u65f6\u95f4\u901a\u77e5\u60a8\uff01';
        requestline = new Hotline();
        requestline.startCityId = $scope.startCityId;
        requestline.endCityId = $scope.endCityId;
        console.log($scope.startCityId);
        requestline.$save(function () {
          return alert(msg);
        });
        return $state.go('index');
      };
    }
  ]);
}.call(this));  //# sourceMappingURL=search.controller.js.map

// Generated by CoffeeScript 1.10.0
(function () {
  angular.module('InterCityBus').config([
    '$stateProvider',
    function ($stateProvider) {
      return $stateProvider.state('search', {
        url: '/search?start&end',
        templateUrl: 'app/search/search.html',
        controller: 'SearchController'
      });
    }
  ]);
  angular.module('InterCityBus.services').factory('Utils', function () {
    return {
      fixTooLongIssue: function () {
        var lineName, w;
        lineName = $('.line_name');
        angular.forEach(lineName, function (item, key) {
          var w1, w2;
          w1 = $(item).find('ul[class=\'start\']').width();
          w2 = $(item).find('ul[class=\'end\']').width();
          return $(item).css('min-width', w1 + w2);
        });
        return;
        w = lineName.width();
        if (w1 + w2 > w) {
          $('ul[class=\'end\']').width(w2).css('right', -(w1 + w2 - w));
          $('.white_bg_right').css('right', -(w1 + w2 - w));
          lineName.height('9.4rem').css('margin-top', 0).css('overflow-x', 'auto').css('overflow-y', 'hidden');
          return lineName.children().each(function (index, item) {
            return $(item).css('margin-top', '1.1rem');
          });
        } else {
          $('ul[class=\'end\']').width('').css('right', '');
          $('.white_bg_right').css('right', '');
          lineName.css('margin-top', '').css('overflow-x', '').css('overflow-y', '');
          return lineName.children().each(function (index, item) {
            return $(item).css('margin-top', '');
          });
        }
      }
    };
  });
}.call(this));  //# sourceMappingURL=search.js.map
