// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('InterCityBus').config(function($stateProvider) {
    return $stateProvider.state('index', {
      url: '/index',
      templateUrl: 'app/index/index.html',
      controller: 'IndexController'
    });
  });

  angular.module('InterCityBus.services').factory('City', function($resource) {
    return $resource('/api/cities/:id', {
      id: '@id'
    }, {
      update: {
        method: "PUT"
      }
    });
  }).factory('Hotline', function($resource) {
    return $resource('/api/hotlines/:id', {
      id: '@id'
    });
  });

}).call(this);

//# sourceMappingURL=index.js.map
