// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('InterCityBus').config(function($stateProvider) {
    return $stateProvider.state('index', {
      url: '/index',
      templateUrl: 'app/index/index.html',
      controller: 'IndexController'
    });
  });

}).call(this);

//# sourceMappingURL=index.js.map
