// Generated by CoffeeScript 1.9.3
(function() {
  var apiRouter, express, router;

  express = require("express");

  router = express.Router();

  apiRouter = require("../api")(router);

  module.exports = apiRouter;

}).call(this);
