// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, _, config, express, fulfillHotlines, model, path, router;

  express = require('express');

  path = require("path");

  router = express.Router();

  _ = require("underscore");

  Promise = require("sequelize").Promise;

  model = require("../lib/model");

  config = require("../config/config");

  router.all("/", function(req, res, next) {
    return res.sendFile(path.join(config.root, 'client/desktop/index.html'));
  });

  router.all("/*", function(req, res, next) {
    return res.sendFile(path.join(config.root, 'client/app/index.html'));
  });

  fulfillHotlines = function(hotline) {
    return hotline.getStartCity().then(function(city) {
      hotline.startCity = {
        name: city.name,
        id: city.id
      };
      return hotline.getEndCity();
    }).then(function(city) {
      hotline.endCity = {
        name: city.name,
        id: city.id
      };
      return hotline;
    });
  };

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.js.map
