// Generated by CoffeeScript 1.10.0
(function() {
  var myapp;

  myapp = angular.module('InterCityBus', ["ui.router", "ngResource", "InterCityBus.services", "InterCityBus.controllers"]);

  myapp.config(function($stateProvider, $urlRouterProvider) {
    return $stateProvider.state('route1', {
      url: "/route1",
      templateUrl: "app/admin/route1.html"
    }).state('route1.list', {
      url: "list",
      templateUrl: "app/admin/route1.list.html",
      controller: function($scope) {
        return $scope.items = ["A", "List", "Of", "Items"];
      }
    }).state('route2', {
      url: "route2",
      templateUrl: "app/admin/route2.html"
    }).state('route2.list', {
      url: "list",
      templateUrl: "app/admin/route2.list.html",
      controller: function($scope) {
        return $scope.things = ["A", "Set", "Of", "Things"];
      }
    });
  });

  angular.module('InterCityBus.services', []).factory('City', function($resource) {
    return $resource('/api/cities/:id', {
      id: '@id'
    }, {
      update: {
        method: "PUT"
      }
    });
  }).factory('Busline', function($resource) {
    return $resource('/api/buslines/:id', {
      id: '@id'
    }, {
      update: {
        method: "PUT"
      }
    });
  }).factory('Company', function($resource) {
    return $resource('/api/companies/:id', {
      id: '@id'
    }, {
      update: {
        method: "PUT"
      }
    });
  }).factory('Phone', function($resource) {
    return $resource('/api/phones/:id', {
      id: '@id'
    }, {
      update: {
        method: "PUT"
      }
    });
  }).factory('Station', function($resource) {
    return $resource('/api/stations/:id', {
      id: '@id'
    }, {
      update: {
        method: "PUT"
      }
    });
  }).factory('Starttime', function($resource) {
    return $resource('/api/starttimes/:id', {
      id: '@id'
    }, {
      update: {
        method: "PUT"
      }
    });
  });

}).call(this);

//# sourceMappingURL=app.js.map
