// Generated by CoffeeScript 1.9.3
(function() {
  var myapp;

  myapp = angular.module('InterCityBus', ["ui.router"]);

  myapp.config(function($stateProvider, $urlRouterProvider) {
    return $stateProvider.state('route1', {
      url: "/route1",
      templateUrl: "app/admin/route1.html"
    }).state('route1.list', {
      url: "list",
      templateUrl: "app/admin/route1.list.html",
      controller: function($scope) {
        return $scope.items = ["A", "List", "Of", "Items"];
      }
    }).state('route2', {
      url: "route2",
      templateUrl: "app/admin/route2.html"
    }).state('route2.list', {
      url: "list",
      templateUrl: "app/admin/route2.list.html",
      controller: function($scope) {
        return $scope.things = ["A", "Set", "Of", "Things"];
      }
    });
  });

}).call(this);
