// Generated by CoffeeScript 1.10.0
(function() {
  var myapp;

  myapp = angular.module('InterCityBus', ["ui.router", "ngCookies", "ngResource", "InterCityBus.services", "InterCityBus.controllers"]).config(function($stateProvider, $urlRouterProvider, $locationProvider, $httpProvider) {
    $locationProvider.html5Mode(true);
    return $httpProvider.interceptors.push('authInterceptor');
  }).factory('authInterceptor', function($rootScope, $q, $cookies, $injector) {
    return {
      request: function(config) {
        config.headers = config.headers || {};
        if ($cookies.get('token')) {
          config.headers.Authorization = 'Bearer ' + $cookies.get('token');
        }
        return config;
      },
      responseError: function(response) {
        var state;
        if (response.status === 401) {
          (state || (state = $injector.get('$state'))).go('login');
          $cookies.remove('token');
          return $q.reject(response);
        } else {
          return $q.reject(response);
        }
      }
    };
  }).run(function($rootScope, $state) {
    return $rootScope.$on('$stateChangeStart', function(event, next) {
      console.log(next);
      console.log(next.url);
      if (next.url === "/") {
        event.preventDefault();
        return $state.go('search');
      }
    });
  });

  angular.module('InterCityBus.services', []);

  angular.module('InterCityBus.controllers', []);

}).call(this);

//# sourceMappingURL=app.js.map
