// Generated by CoffeeScript 1.9.3
(function() {
  var conf, path;

  path = require("path");

  conf = {
    dialect: 'mysql',
    maxHotlines: 6,
    root: path.normalize(__dirname + '/../..')
  };

  module.exports = conf;

}).call(this);
