// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('InterCityBus').config(function($stateProvider) {
    return $stateProvider.state('buslines', {
      url: 'buslines',
      templateUrl: 'app/admin/buslines/buslines.html',
      controller: 'BuslinesCtrl'
    });
  });

}).call(this);
