// Generated by CoffeeScript 1.9.3
(function() {
  var Sequelize, sequelize2;

  Sequelize = require('sequelize');

  sequelize2 = new Sequelize('database', 'czz', 'sb', {
    host: 'localhost',
    dialect: 'sqlite',
    logging: false,
    pool: {
      max: 5,
      min: 0,
      idle: 10000
    },
    storage: './database.sqite'
  });

  module.exports = sequelize2;

}).call(this);
