// Generated by CoffeeScript 1.9.3
(function() {
  var Sequelize, conf, sequelize2;

  Sequelize = require('sequelize');

  conf = require('../etc/config');

  sequelize2 = new Sequelize('intercitybus', 'root', '', {
    host: 'localhost',
    dialect: "mysql",
    timezone: '+08:00',
    logging: true,
    pool: {
      max: 5,
      min: 0,
      idle: 10000
    }
  });

  module.exports = sequelize2;

}).call(this);
