// Generated by CoffeeScript 1.10.0
(function() {
  var User, compose, expressJwt, hasRole, isAuthenticated, jwt, secret, setTokenCookie, signToken, validateJwt;

  jwt = require('jsonwebtoken');

  expressJwt = require('express-jwt');

  compose = require('composable-middleware');

  User = require('../lib/model').User;

  secret = 'dsafsafas';

  validateJwt = expressJwt({
    secret: secret
  });

  isAuthenticated = function() {
    return compose().use(function(req, res, next) {
      if (req.query && req.query.hasOwnProperty('access_token')) {
        req.headers.authorization = 'Bearer ' + req.query.access_token;
      }
      return validateJwt(req, res, next);
    }).use(function(req, res, next) {
      return User.find({
        where: {
          id: req.user.id
        }
      }).then(function(user) {
        if (!user) {
          return res.status(401).end();
        }
        req.user = user;
        return next();
      })["catch"](function(err) {
        return next(err);
      });
    });
  };


  /*
   * Checks if the user role meets the minimum requirements of the route
   */

  hasRole = function(roleRequired) {
    var meetsRequirements;
    if (!roleRequired) {
      throw new Error('Required role needs to be set');
    }
    return compose().use(isAuthenticated()).use(meetsRequirements = function(req, res, next) {
      if (config.userRoles.indexOf(req.user.role) >= config.userRoles.indexOf(roleRequired)) {
        return next();
      } else {
        return res.status(403).send('Forbidden');
      }
    });
  };


  /*
   * Returns a jwt token signed by the app secret
   */

  signToken = function(id, role) {
    return jwt.sign({
      id: id,
      role: role
    }, secret, {
      expiresInMinutes: 60 * 5
    });
  };


  /*
   * Set token cookie directly for oAuth strategies
   */

  setTokenCookie = function(req, res) {
    var token;
    if (!req.user) {
      return res.status(404).send('Something went wrong, please try again.');
    }
    token = signToken(req.user.id, req.user.role);
    res.cookie('token', token);
    return res.redirect('/');
  };

  exports.isAuthenticated = isAuthenticated;

  exports.hasRole = hasRole;

  exports.signToken = signToken;

  exports.setTokenCookie = setTokenCookie;

}).call(this);

//# sourceMappingURL=auth.service.js.map
