// Generated by CoffeeScript 1.10.0
(function() {
  var controller;

  controller = require("./cities.controller");

  module.exports = function(router) {
    router.get("/test", function(req, res, next) {
      return res.send("test ok");
    });
    router.get("/cities", controller.index);
    router.get("/cities/:id", controller.show);
    router.post("/cities", controller.create);
    router.put("/cities/:id", controller.update);
    router.patch('/cities/:id', controller.update);
    return router["delete"]('/cities/:id', controller.destroy);
  };

}).call(this);

//# sourceMappingURL=index.js.map
