// Generated by CoffeeScript 1.10.0
(function() {
  var auth, controller;

  controller = require("./cities.controller");

  auth = require('../../auth/auth.service');

  module.exports = function(router) {
    router.get("/test", function(req, res, next) {
      return res.send("test ok");
    });
    router.get("/cities", controller.index);
    router.get("/cities/:id", controller.show);
    router.post("/cities", auth.hasRole('admin'), controller.create);
    router.put("/cities/:id", auth.hasRole('admin'), controller.update);
    router.patch('/cities/:id', auth.hasRole('admin'), controller.update);
    return router["delete"]('/cities/:id', auth.hasRole('admin'), controller.destroy);
  };

}).call(this);

//# sourceMappingURL=index.js.map
