// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('InterCityBus').config(function($stateProvider) {
    return $stateProvider.state('busline', {
      url: '/busline',
      templateUrl: 'app/busline/busline.html',
      controller: 'BuslineController'
    });
  });

}).call(this);

//# sourceMappingURL=busline.js.map
