// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('InterCityBus').config(function($stateProvider) {
    return $stateProvider.state('busline', {
      url: '/busline/:id',
      templateUrl: 'app/busline/busline.html',
      controller: 'BuslineController'
    });
  });

  angular.module('InterCityBus.services').factory('Busline', function($resource) {
    return $resource('/api/buslines/:id', {
      id: '@id'
    }, {
      update: {
        method: "PUT"
      }
    });
  });

}).call(this);

//# sourceMappingURL=busline.js.map
