// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('InterCityBus').config(function($stateProvider) {
    return $stateProvider.state('login', {
      url: '/admin/login',
      templateUrl: 'app/admin/account/login/login.html',
      controller: 'AdminLoginCtrl'
    }).state('logout', {
      url: '/admin/logout?referrer',
      referrer: 'main',
      template: '',
      controller: function($state, Auth) {
        var referrer;
        referrer = $state.params.referrer || $state.current.referrer || 'main';
        Auth.logout();
        return $state.go(referrer);
      }
    }).state('signup', {
      url: '/signup',
      templateUrl: 'app/account/signup/signup.html',
      controller: 'SignupCtrl'
    }).state('settings', {
      url: '/settings',
      templateUrl: 'app/account/settings/settings.html',
      controller: 'SettingsCtrl',
      authenticate: true
    });
  }).run(function($rootScope) {
    return $rootScope.$on('$stateChangeStart', function(event, next, nextParams, current) {
      if (next.name === 'logout' && current && current.name && !current.authenticate) {
        return next.referrer = current.name;
      }
    });
  });

}).call(this);

//# sourceMappingURL=account.js.map
