// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    up: function(queryInterface, Sequelize) {
      return queryInterface.addColumn('hotlines', 'requestCount', {
        type: Sequelize.INTEGER,
        defaultValue: 0
      });
    },
    down: function(queryInterface, Sequelize) {}
  };

}).call(this);

//# sourceMappingURL=201511190118_add_column_to_hotline.js.map
