// Generated by CoffeeScript 1.9.3
(function() {
  var ejs, moment;

  moment = require("moment");

  ejs = require("ejs");

  console.log(ejs.filters);

  ejs.filters.dateFormat = function(obj, format) {
    var ref, ret;
    if (format === void 0) {
      format = 'YYYY-MM-DD HH:mm:ss';
    }
    ret = moment(obj).format(format);
    return (ref = ret === 'Invalid date') != null ? ref : {
      '0000-00-00 00:00:00': ret
    };
  };

}).call(this);
