// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('InterCityBus').config(function($stateProvider) {
    return $stateProvider.state('search', {
      url: '/search?start&end',
      templateUrl: 'app/search/search.html',
      controller: 'SearchController'
    });
  });

  angular.module('InterCityBus.services').factory('Utils', function() {
    return {
      fixTooLongIssue: function() {
        var lineName, w;
        lineName = $(".line_name");
        angular.forEach(lineName, function(item, key) {
          var w1, w2;
          w1 = $(item).find("ul[class='start']").width();
          w2 = $(item).find("ul[class='end']").width();
          return $(item).css("min-width", w1 + w2);
        });
        return;
        w = lineName.width();
        if (w1 + w2 > w) {
          $("ul[class='end']").width(w2).css("right", -(w1 + w2 - w));
          $(".white_bg_right").css("right", -(w1 + w2 - w));
          lineName.height("9.4rem").css("margin-top", 0).css("overflow-x", "auto").css("overflow-y", "hidden");
          return lineName.children().each(function(index, item) {
            return $(item).css("margin-top", "1.1rem");
          });
        } else {
          $("ul[class='end']").width('').css('right', '');
          $(".white_bg_right").css("right", '');
          lineName.css("margin-top", '').css("overflow-x", '').css("overflow-y", '');
          return lineName.children().each(function(index, item) {
            return $(item).css("margin-top", "");
          });
        }
      }
    };
  });

}).call(this);

//# sourceMappingURL=search.js.map
