// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('InterCityBus').config(function($stateProvider) {
    return $stateProvider.state('search', {
      url: '/search',
      templateUrl: 'app/search/search.html',
      controller: 'SearchController'
    });
  });

}).call(this);

//# sourceMappingURL=search.js.map
