// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('InterCityBus').config(function($stateProvider) {
    return $stateProvider.state('search', {
      url: '/search?start&end',
      templateUrl: 'app/search/search.html',
      controller: 'SearchController'
    });
  });

  angular.module('InterCityBus.services').factory('Utils', function() {
    return {
      fixTooLongIssue: function() {
        var lineName, w, w1, w2;
        lineName = $(".line_name");
        w1 = $("ul[class='start']").width();
        w2 = $("ul[class='end']").width();
        w = lineName.width();
        if (w1 + w2 > w) {
          console.log('ok fix it');
          $("ul[class='end']").width(w2);
          $("ul[class='end']").css("right", -(w1 + w2 - w));
          lineName.css("max-width", w).height("9.4rem").css("margin-top", 0).css("overflow-x", "auto").css("overflow-y", "hidden");
          $(".white_bg_right").css("right", -(w1 + w2 - w));
          return lineName.children().each(function(index, item) {
            return $(item).css("margin-top", "1.1rem");
          });
        }
      }
    };
  });

}).call(this);

//# sourceMappingURL=search.js.map
